server:
  servlet:
    context-path: /api/
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://root:SMsNQWfaiZKjSQMfk3sD@containers-us-west-105.railway.app:6886/railway
    username: root
    password: SMsNQWfaiZKjSQMfk3sD